[package]
name = "grot"
version = "0.1.0"
authors = ["Zomerfaun <zomerfaun@gmail.com>"]

[dependencies]
sdl2 = "0.31.0"
failure = "0.1.1"
floating-duration = { git = "https://github.com/torkleyy/floating-duration.git" }
pretty_env_logger = "0.2.2"
log = "0.4.1"
